### PR TITLE
Workaround for #50

### PR DESCRIPTION
**Pull request by ajtucker**
Implement workaround for distributions with no issued dates.

### CODE REVIEW

**Comment by cadmiumcat** [comment]
Is this PR still relevant?

**Comment by mikeAdamss** [comment]
yes, its an enhancement to avoid us using a long standing work around, but the work around works so it's relevant but not a priority.

**Comment by cadmiumcat** [comment]
So this PR needs some context added so that someone can review it.

Otherwise, it can be changed for a draft request as it's not ready for review

**Comment by RedWalters** [comment]
Looks good, makes sense
All tests pass on my messy local as well

**Review by RedWalters — APPROVED** [review]

**Pull request merged**
