### PR TITLE
Fix pmdcat:DataCube not expanding correctly

### PR DESCRIPTION
**Pull request by rossbowen**
See https://github.com/GSS-Cogs/gss-utils/issues/203.

### CODE REVIEW

**Comment by ajtucker** [comment]
It'd be good to have test coverage of this.

**Comment by ajtucker** [comment]
I wonder whether the fix is to remove the declaration from `dsd.py`, as it's already declared properly in `pmdcat.py`. I think it's currently getting both `<pmdcat:DataCube>` and `pmdcat:DataCube` types, e.g. https://staging.gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-services-by-industry-country-and-service-type-exports%2Fpcn%23dataset

**Comment by rossbowen** [comment]
I think you're right. It's appearing in the `.trig` which I think is coming from here:

https://github.com/GSS-Cogs/gss-utils/blob/734a6b1876a06bd5bc79e9f50a131a4235be58c9/gssutils/scrape.py#L384-L385

**Review by ajtucker — APPROVED** [review]
Thanks for tracking this down!

I added a minimal check for the right triple, though this won't guard against it being wrong.

Note that we're accreting technical debt :)

**Pull request merged**
